In [1]:
import sys
sys.path
sys.path.append('../')

from diamonds import customSGD, normal_equation

In [2]:
customSGD.grad_mse_step_test()

X values 
[[1. 4. 7.]
 [1. 2. 6.]]
Iter 0 theta: [1.02  0.05  0.125]
RMSE error: 1.5076
Iter 1 theta: [1.030175 0.0694   0.185575]
RMSE error: 1.2881
Iter 2 theta: [1.03572887 0.07443975 0.21586425]
RMSE error: 1.2297
Iter 3 theta: [1.03910722 0.07275106 0.23191162]
RMSE error: 1.2118
Iter 4 theta: [1.04145936 0.06792041 0.241257  ]
RMSE error: 1.2031
Iter 5 theta: [1.04332545 0.06163319 0.24744383]
RMSE error: 1.1966
Iter 6 theta: [1.04495935 0.05468134 0.25213741]
RMSE error: 1.1905
Iter 7 theta: [1.04648038 0.04743694 0.25612039]
RMSE error: 1.1846
Iter 8 theta: [1.04794465 0.04007476 0.25976061]
RMSE error: 1.1787
Iter 9 theta: [1.04937852 0.03267682 0.263231  ]
RMSE error: 1.1729
Iter 10 theta: [1.05079441 0.02528159 0.26661285]
RMSE error: 1.1671
Iter 11 theta: [1.05219818 0.01790703 0.26994444]
RMSE error: 1.1613
Iter 12 theta: [1.0535926  0.01056149 0.27324376]
RMSE error: 1.1555
Iter 13 theta: [1.05497899 0.00324881 0.27651935]
RMSE error: 1.1498
Iter 14 theta: [ 1.05635798 -0

In [3]:
customSGD.SGD_test()

X values 
[[-0.7091967  -0.14618925 -0.36215329 ...  0.34765372 -0.0075784
   0.15267216]
 [-0.28091714 -0.62462463  0.00309214 ...  0.10640227 -2.00292155
   1.48585708]
 [-0.39960587  0.75726928 -1.48852538 ...  1.31399074  0.83838258
  -0.57811205]
 ...
 [ 0.42863682  0.7651874  -1.93520723 ... -0.60803077  2.14867073
   0.77838627]
 [-0.44609589  0.40551133  0.26715317 ... -1.29640459 -1.15313465
   1.80726751]
 [ 0.65797317 -0.53425629 -1.16912471 ... -0.51444724  1.3530039
   1.61541063]]

Full batch
Number of samples: 40000
Number of parameters: 26
It: 1 Batch: 1 Epoch 0 Error: 14179.10158528 lr: 0.01000000 
It: 100 Batch: 1 Epoch 99 Error: 1918.97289709 lr: 0.01000000 
It: 200 Batch: 1 Epoch 199 Error: 255.24077228 lr: 0.01000000 
It: 300 Batch: 1 Epoch 299 Error: 34.13036231 lr: 0.01000000 
It: 400 Batch: 1 Epoch 399 Error: 4.67032413 lr: 0.01000000 
It: 500 Batch: 1 Epoch 499 Error: 0.73502265 lr: 0.01000000 
Finished 
 It: 500 Batch: 1 Epoch 499 Error: 0.73502265 lr: 0.01000

In [4]:
normal_equation.normal_equation_test()

('Theta', array([ 4. , -1.5,  1. ]))
RMSE error: 3.0000


In [5]:
customSGD.get_batch_test()

(0, 100, (100, 3), (100,), 1, 100, 0)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
(1, 105, (5, 3), (5,), 2, 100, 0)
[100 101 102 103 104]
(2, 205, (100, 3), (100,), 1, 100, 1)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [6]:
import numpy as np
count = 2
X = np.ones((count, 3))
y = np.array(range(0, count))
b_it = 0
b_sz = 1
epoch = 0
it = 0
sz = 0
while epoch < 1:
    X_, y_, b_it, epoch = customSGD.get_batch(X, y, b_it, b_sz, epoch)
    sz += X_.shape[0]
    print(it, sz, X_.shape, y_.shape, b_it, b_sz, epoch)
    print(y_)
    it += 1

(0, 1, (1, 3), (1,), 1, 1, 0)
[0]
(1, 2, (1, 3), (1,), 2, 1, 0)
[1]
(2, 2, (0, 3), (0,), 3, 1, 0)
[]
(3, 3, (1, 3), (1,), 1, 1, 1)
[0]
