In [1]:
import sys
sys.path
sys.path.append('../')

from diamonds import customSGD, normal_equation

In [2]:
customSGD.grad_mse_step_test()

X values 
[[1. 4. 7.]
 [1. 2. 6.]]
Iter 0 theta: [1.02  0.05  0.125]
RMSE error: 1.5076
Iter 1 theta: [1.030175 0.0694   0.185575]
RMSE error: 1.2881
Iter 2 theta: [1.03572887 0.07443975 0.21586425]
RMSE error: 1.2297
Iter 3 theta: [1.03910722 0.07275106 0.23191162]
RMSE error: 1.2118
Iter 4 theta: [1.04145936 0.06792041 0.241257  ]
RMSE error: 1.2031
Iter 5 theta: [1.04332545 0.06163319 0.24744383]
RMSE error: 1.1966
Iter 6 theta: [1.04495935 0.05468134 0.25213741]
RMSE error: 1.1905
Iter 7 theta: [1.04648038 0.04743694 0.25612039]
RMSE error: 1.1846
Iter 8 theta: [1.04794465 0.04007476 0.25976061]
RMSE error: 1.1787
Iter 9 theta: [1.04937852 0.03267682 0.263231  ]
RMSE error: 1.1729
Iter 10 theta: [1.05079441 0.02528159 0.26661285]
RMSE error: 1.1671
Iter 11 theta: [1.05219818 0.01790703 0.26994444]
RMSE error: 1.1613
Iter 12 theta: [1.0535926  0.01056149 0.27324376]
RMSE error: 1.1555
Iter 13 theta: [1.05497899 0.00324881 0.27651935]
RMSE error: 1.1498
Iter 14 theta: [ 1.05635798 -0

In [3]:
customSGD.SGD_test()

X values 
[[4. 7.]
 [2. 6.]]
Full batch
Number of samples: 2
Number of parameters: 3
It: 1 Batch: 1 Epoch 0 Error: 1.89170983 lr: 0.01000000 
It: 2 Batch: 1 Epoch 1 Error: 0.95965420 lr: 0.01000000 
It: 3 Batch: 1 Epoch 2 Error: 0.74845112 lr: 0.01000000 
It: 4 Batch: 1 Epoch 3 Error: 0.69650499 lr: 0.01000000 
It: 5 Batch: 1 Epoch 4 Error: 0.67978398 lr: 0.01000000 
It: 6 Batch: 1 Epoch 5 Error: 0.67089447 lr: 0.01000000 
It: 7 Batch: 1 Epoch 6 Error: 0.66378593 lr: 0.01000000 
It: 8 Batch: 1 Epoch 7 Error: 0.65712157 lr: 0.01000000 
It: 9 Batch: 1 Epoch 8 Error: 0.65060564 lr: 0.01000000 
It: 10 Batch: 1 Epoch 9 Error: 0.64417232 lr: 0.01000000 
It: 11 Batch: 1 Epoch 10 Error: 0.63780660 lr: 0.01000000 
It: 12 Batch: 1 Epoch 11 Error: 0.63150466 lr: 0.01000000 
It: 13 Batch: 1 Epoch 12 Error: 0.62526519 lr: 0.01000000 
It: 14 Batch: 1 Epoch 13 Error: 0.61908740 lr: 0.01000000 
It: 15 Batch: 1 Epoch 14 Error: 0.61297067 lr: 0.01000000 
It: 16 Batch: 1 Epoch 15 Error: 0.60691436 lr: 0.

In [4]:
normal_equation.normal_equation_test()

('Theta', array([ 4. , -1.5,  1. ]))
RMSE error: 3.0000


In [5]:
customSGD.get_batch_test()

(0, 100, (100, 3), (100,), 1, 100, 0)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
(1, 105, (5, 3), (5,), 2, 100, 0)
[100 101 102 103 104]
(2, 205, (100, 3), (100,), 1, 100, 1)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [6]:
import numpy as np
count = 2
X = np.ones((count, 3))
y = np.array(range(0, count))
b_it = 0
b_sz = 1
epoch = 0
it = 0
sz = 0
while epoch < 1:
    X_, y_, b_it, epoch = customSGD.get_batch(X, y, b_it, b_sz, epoch)
    sz += X_.shape[0]
    print(it, sz, X_.shape, y_.shape, b_it, b_sz, epoch)
    print(y_)
    it += 1

(0, 1, (1, 3), (1,), 1, 1, 0)
[0]
(1, 2, (1, 3), (1,), 2, 1, 0)
[1]
(2, 2, (0, 3), (0,), 3, 1, 0)
[]
(3, 3, (1, 3), (1,), 1, 1, 1)
[0]
